name: event_minder  # Project Name
description: A Flutter app for event management with face recognition and cloud features.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"  # Ensures compatibility with Flutter 3.x and Dart 3.x

dependencies:
  flutter:
    sdk: flutter

  # UI and Design
  google_fonts: ^6.1.0       # Custom fonts for a polished UI

  # Firebase (Cloud Infrastructure and Authentication)
  firebase_core: ^3.11.0     # Core Firebase SDK
  firebase_auth: ^5.4.2      # User authentication (login/signup)
  cloud_firestore: ^5.6.3    # Firestore for storing events, users, and attendance
  firebase_storage: ^12.4.2  # Storage for images (e.g., face data, certificates)

  # Networking and APIs
  http: ^1.3.0              # For API calls (e.g., NLP or backend integration)

  # Image Handling
  image_picker: ^1.1.2      # Capture images from camera/gallery for face recognition

  # Face Recognition
  google_ml_kit: ^0.18.0    # Google ML Kit for face detection and recognition

  # State Management
  provider: ^6.1.2          # Simple state management for app-wide data

  # Utilities
  intl: ^0.19.0             # Date and time formatting for events
  flutter_secure_storage: ^9.2.0  # Secure storage for tokens or sensitive data
  path_provider: ^2.1.5     # Access file system (e.g., for saving certificates)
  pdf: ^3.11.0              # Generate PDF certificates of completion
  share_plus: ^10.0.2       # Share certificates or event details

dev_dependencies:
  flutter_test:
    sdk: flutter  # For unit and widget testing
  flutter_lints: ^4.0.0     # Linting for code quality

flutter:
  uses-material-design: true  # Enables Material Design components
  assets:
    - assests/images/img.png