name: event_minder
description: A Flutter app for event management with face recognition and cloud features.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase (Cloud Infrastructure and Authentication)
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0

  # UI and Design
  google_fonts: ^6.2.1
  lottie: ^3.3.1

  # Networking and APIs
  http: ^1.3.0

  # Image Handling
  image_picker: ^1.1.2

  # Face Recognition (ML Kit)
  google_mlkit_face_detection: ^0.10.0

  # State Management
  provider: ^6.1.2

  # Utilities
  intl: ^0.19.0
  flutter_secure_storage: ^9.2.0
  path_provider: ^2.1.5
  pdf: ^3.11.0
  share_plus: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/animations/Animation1.json
    - assets/animations/login.json
    - assets/animations/register.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo.png"